apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 7000
  type: LoadBalancer
  externalIPs:
  - 192.168.58.2
